# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiDemo10.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1234, 813)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 981, 611))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButtonPlay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPlay.setGeometry(QtCore.QRect(20, 640, 93, 28))
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.pushButtonPause = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPause.setGeometry(QtCore.QRect(130, 640, 93, 28))
        self.pushButtonPause.setObjectName("pushButtonPause")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1234, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionTrans = QtWidgets.QAction(MainWindow)
        self.actionTrans.setObjectName("actionTrans")
        self.actionRowCaption = QtWidgets.QAction(MainWindow)
        self.actionRowCaption.setObjectName("actionRowCaption")
        self.actionCutVideo = QtWidgets.QAction(MainWindow)
        self.actionCutVideo.setObjectName("actionCutVideo")
        self.actionVideo2Image = QtWidgets.QAction(MainWindow)
        self.actionVideo2Image.setObjectName("actionVideo2Image")
        self.actionImage2Video = QtWidgets.QAction(MainWindow)
        self.actionImage2Video.setObjectName("actionImage2Video")
        self.actionPart2Video = QtWidgets.QAction(MainWindow)
        self.actionPart2Video.setObjectName("actionPart2Video")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionSave)
        self.menu.addSeparator()
        self.menu.addAction(self.actionQuit)
        self.menu_2.addAction(self.actionTrans)
        self.menu_2.addAction(self.actionImage2Video)
        self.menu_2.addAction(self.actionPart2Video)
        self.menu_3.addAction(self.actionRowCaption)
        self.menu_3.addAction(self.actionCutVideo)
        self.menu_3.addAction(self.actionVideo2Image)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonPlay.setText(_translate("MainWindow", "播放"))
        self.pushButtonPause.setText(_translate("MainWindow", "暂停"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "制作"))
        self.menu_3.setTitle(_translate("MainWindow", "后期"))
        self.actionOpen.setText(_translate("MainWindow", "打开文件"))
        self.actionSave.setText(_translate("MainWindow", "保存文件"))
        self.actionQuit.setText(_translate("MainWindow", "退出"))
        self.actionTrans.setText(_translate("MainWindow", "图像转场"))
        self.actionRowCaption.setText(_translate("MainWindow", "滚动字幕"))
        self.actionCutVideo.setText(_translate("MainWindow", "截取视频片段"))
        self.actionVideo2Image.setText(_translate("MainWindow", "视频转化为动画图像"))
        self.actionImage2Video.setText(_translate("MainWindow", "基于图像制作动画图像"))
        self.actionPart2Video.setText(_translate("MainWindow", "基于图像制作局部运动的动画图像"))
